/* SS ENTERPRISES — ID CARD QR / COMPANY DETAILS PATCH
   Additive patch: keeps the existing admin ID-card generator intact.
*/
(function(){
  'use strict';
  const OFFICIAL_URL = 'https://ssenterprisesservice.online/';
  const EMPLOYEE_URL = OFFICIAL_URL + 'employee.html';
  const COMPANY = {
    name: 'SS Enterprises',
    address: 'Donar Road, Darbhanga, Bihar',
    phone: '+91 73600 25302',
    email: 'info@ssenterprisesservice.online',
    website: 'ssenterprisesservice.online',
    udyam: 'BR-10-0011079'
  };

  // Make every QR generated by the existing admin code use the official URL.
  function patchQRCode(){
    if(!window.QRCode || window.__ssQrPatched) return;
    const Original = window.QRCode;
    function PatchedQRCode(element, options){
      if(typeof options === 'string') options = {text: options};
      options = Object.assign({}, options || {});
      let text = String(options.text || '');
      if(/employee\.html|ssenterprisesservice\.(online|com)|ss-enterprises-premium-website/i.test(text)){
        const m = text.match(/[?&]employee=([^&#]+)/i);
        text = EMPLOYEE_URL + (m ? '?employee=' + encodeURIComponent(decodeURIComponent(m[1])) : '');
      }
      options.text = text;
      return new Original(element, options);
    }
    Object.keys(Original).forEach(k=>{ try{ PatchedQRCode[k]=Original[k]; }catch(e){} });
    window.QRCode = PatchedQRCode;
    window.__ssQrPatched = true;
  }

  function addCompanyDetails(root){
    if(!root) return;
    const backs = root.querySelectorAll('.id-back');
    backs.forEach(back=>{
      const body = back.querySelector('.id-back-body') || back;
      let box = body.querySelector('.ss-id-company-details');
      if(box) return;
      box = document.createElement('div');
      box.className = 'ss-id-company-details';
      box.innerHTML = '<strong>SS ENTERPRISES</strong>'+
        '<span>Donar Road, Darbhanga, Bihar</span>'+
        '<span>Mob: +91 73600 25302</span>'+
        '<span>Email: info@ssenterprisesservice.online</span>'+
        '<span>Website: ssenterprisesservice.online</span>'+
        '<span>Udyam/MSME: BR-10-0011079</span>';
      body.insertBefore(box, body.firstChild || null);
    });
  }

  // Patch QRCode immediately; admin.js is loaded after this file.
  patchQRCode();

  function start(){
    const style = document.createElement('style');
    style.textContent = '.ss-id-company-details{margin:1.8mm 0 2.2mm;padding:2mm;border:1px solid rgba(201,155,46,.55);border-radius:2mm;background:rgba(255,255,255,.07);font-family:Arial,sans-serif;color:#fff;line-height:1.38}.ss-id-company-details strong{display:block;font-size:3mm;letter-spacing:.3mm;margin-bottom:1mm}.ss-id-company-details span{display:block;font-size:2.05mm;word-break:break-word}.id-back .ss-id-company-details{font-size:inherit}';
    document.head.appendChild(style);
    const target = document.getElementById('idCardPreview');
    if(target){
      const obs = new MutationObserver(()=>addCompanyDetails(target));
      obs.observe(target,{childList:true,subtree:true});
      addCompanyDetails(target);
    }
  }

  // admin.html loads QRCode before admin.js, so patch as early as possible.
  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start, {once:true});
  else start();
  // Retry once in case the CDN script was still initializing.
  setTimeout(patchQRCode, 50);
})();
